# Generated by Django 4.2.7 on 2024-09-06 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user_by',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='initial_total',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='service_fee',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
